FROM python:3.10-slim
RUN adduser --disabled-password dbmaker
WORKDIR /home/dbmaker/app
RUN apt update && apt install -y nano

COPY requirements.txt /home/dbmaker
RUN pip3 install -r /home/dbmaker/requirements.txt

COPY config/odbcinst.ini /etc/odbcinst.ini
COPY config/odbc.ini /etc/odbc.ini
COPY config/ /config/

ENV 	TZ=America/Argentina/Buenos_Aires \
		DB_SETTINGS=/config/debug/db-settings.env \
		DB_CREDENTIALS=/config/debug/db-credentials.env \
		JSONPATH=/config/sanjorge_secrets.json \
		LOG_PATH=/home/dbmaker/logs \
		DEBUG=True
